apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: confluent-kafka
          image: idowuilekura/confluent_kafka_orders
          env:
            - name: SNOWFLAKE_USER
              valueFrom:
                configMapKeyRef:
                  name: my-configmaps
                  key: snowflakeuser
            - name: SNOWFLAKE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-configmaps
                  key: snowflakepassword
            - name: SNOWFLAKE_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: my-configmaps
                  key: snowflakeaccount
            - name: SNOWFLAKE_WAREHOUSE
              value: {{ .Values.datawarehouse }}
            - name: SNOWFLAKE_DATABASE
              value: {{ .Values.database }}
            - name: BOOTSTRAP_SERVERS
              value: $BOOTSTRAP_SERVERS
            - name: SECURITY_PROTOCOL
              value: $SECURITY_PROTOCOL
            - name: SASL_MECHANISMS
              value: $SASL_MECHANISMS
            - name: SASL_USERNAME
              value: $SASL_USERNAME
            - name: SASL_PASSWORD
              value: $SASL_PASSWORD
            - name: SESSION_TIMEOUT_MS
              valueFrom:
                configMapKeyRef:
                  name: my-configmaps
                  key: sessiontimeoutms
            - name: SNOWFLAKE_TABLE_TRANSACTION
              valueFrom:
                configMapKeyRef:
                  name: my-configmaps
                  key: snowflaketablename_transaction
            - name: SNOWFLAKE_TABLE_ANALYTICAL
              valueFrom:
                configMapKeyRef:
                  name: my-configmaps
                  key: snowflaketablename_analytical
            # imagePullPolicy: Never
            # asa
          resources:
            limits:
              memory: 700Mi
              cpu: 700m
            requests:
              memory: 600Mi
              cpu: 600m
          ports:
            - containerPort: 9092

<<<<<<< HEAD:confluenthelm/templates/deployment.yaml
=======
            
>>>>>>> e3acfa74b9eed3e37dc24ae03a1f69c15fcffc4b:shopileft_src/deployment.yaml
