apiVersion: v1
kind: ConfigMap
metadata: 
    name: my-configmaps
    namespace: {{ .Values.namespace }}
data:
    snowflakeuser: ${SNOWFLAKE_USER}
    snowflakepassword: ${SNOWFLAKE_PASSWORD}
    sessiontimeoutms: '45000'
    snowflakeaccount: ${SNOWFLAKE_ACCOUNT}
    snowflaketablename_transaction: ${SNOWFLAKE_TABLE_TRANSACTION}
    snowflaketablename_analytical: ${SNOWFLAKE_TABLE_ANALYTICAL}

