apiVersion: v1
kind: ConfigMap
metadata: 
    name: my-configmaps
    namespace: {{ .Values.namespace }}
data:
    snowflakeuser: EKABAGUDDY
    snowflakepassword: v8kMV6LQ8#H97Dh
    sessiontimeoutms: '45000'
    snowflakeaccount: nf33328.uk-south.azure
    snowflaketablename_transaction: orders_shopileft_transaction
    snowflaketablename_analytical: orders_shopileft_analytical

