name: confluent kafka workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        utils-path: ./confluent_streaming_project/shopileft_src/utils

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install azure cli
        run: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
      - uses: azure/setup-kubectl@v3
        with: 
          version: 'latest'
        id: install



      # Runs a single command using the runners shell
      - name: Install the dependencies
        run: |
            pip install -r requirements.txt
            pip install pytest
            export PYTHONPATH=$PYTHONPATH:utils
           
            ls

      # Runs a set of commands using the runners shell
      - name: Test the consumer
        env: 
          BOOTSTRAP_SERVERS_TEST: ${{ secrets.BOOTSTRAP_SERVERS_TEST }}
          SASL_MECHANISMS_TEST: ${{ secrets.SASL_MECHANISMS_TEST }}
          SASL_USERNAME_TEST: ${{ secrets.SASL_USERNAME_TEST }}
          SASL_PASSWORD_TEST: ${{ secrets.SASL_PASSWORD_TEST }}
          SESSION_TIMEOUT_MS_TEST: ${{ secrets.SESSION_TIMEOUT_MS_TEST }}
          SECURITY_PROTOCOL_TEST: ${{ secrets.SECURITY_PROTOCOL_TEST }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD}}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_TABLE_TRANSACTIONS: ${{ secrets.SNOWFLAKE_TABLE_TRANSACTIONS }}
          SNOWFLAKE_ACCOUNT_ANALYTICAL: ${{ secrets.SNOWFLAKE_ACCOUNT_ANALYTICAL }}

        run:  | 
             export PYTHONPATH=$PYTHONPATH:utils
             pytest shopileft_test/test_producer.py
             pytest shopileft_test/test_consumed_loaded.py

        

